# Generated by Django 4.0.4 on 2022-05-10 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='about/')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('link_telegram', models.URLField(default='')),
                ('link_instagram', models.URLField(default='')),
                ('link_vk', models.URLField(default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('link_telegram', models.URLField()),
                ('link_website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email_or_phone', models.CharField(default='', max_length=100)),
                ('message', models.TextField(max_length=256)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
