# Generated by Django 4.0.4 on 2022-05-04 18:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(blank=True, max_length=100, null=True)),
                ('head_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('head_teachers', models.CharField(blank=True, max_length=100, null=True)),
                ('teachers_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='about/')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('proficiency_level', ckeditor.fields.RichTextField()),
                ('bio', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('message', models.TextField(max_length=256)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='about.about')),
            ],
        ),
    ]
