# Generated by Django 4.0.4 on 2022-05-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='head_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_teachers',
        ),
        migrations.RemoveField(
            model_name='about',
            name='head_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='teachers_description',
        ),
    ]
