# Generated by Django 4.0.4 on 2022-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_head_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='proficiency_level',
            field=models.CharField(max_length=100),
        ),
    ]
