# Generated by Django 4.0.4 on 2022-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_bio_alter_about_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='proficiency_level',
            field=models.CharField(max_length=100),
        ),
    ]
