# Generated by Django 4.0.4 on 2022-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_bio_alter_about_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='link_instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='link_telegram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='link_vk',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
