# Generated by Django 4.0.4 on 2022-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
    ]
