# Generated by Django 4.0.4 on 2022-05-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_link_instagram_about_link_telegram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='email_or_phone',
        ),
    ]
