# Generated by Django 4.0.4 on 2022-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_email_feedback_email_or_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('link_telegram', models.URLField()),
                ('link_website', models.URLField()),
            ],
        ),
    ]
