# Generated by Django 4.0.4 on 2022-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_n_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
