# Generated by Django 4.0.4 on 2022-05-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_n_events', '0003_post_head_description_post_head_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_title',
        ),
    ]
