# Generated by Django 4.0.4 on 2022-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_n_events', '0004_remove_post_head_description_remove_post_head_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
