# Generated by Django 4.0.4 on 2022-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='head_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='head_slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='head_title',
        ),
    ]
