# Generated by Django 4.0.5 on 2022-07-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_head_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['create_at']},
        ),
    ]
