# Generated by Django 4.0.4 on 2022-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_head_description_course_head_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
